// C++ source emitter implementation.
#include "mlk/backend/cpp_emitter.h"

#include "mlk/ir/math_op.h"

#include <cstdio>

namespace mlk {

namespace {
void emitCompute(std::string& out, MathOp op, SymbolTable& symbols) {
    // Scalar C99-style math (vectorized by the consuming compiler; vector
    // width recorded as a schedule pragma comment — Rule 148).
    const char* expr = nullptr;
    switch (op) {  // Rule 78: exhaustive over scalar-realizable ops
        case MathOp::Add: expr = "x[i] + y[i]"; break;
        case MathOp::Sub: expr = "x[i] - y[i]"; break;
        case MathOp::Mul: expr = "x[i] * y[i]"; break;
        case MathOp::Div: expr = "x[i] / y[i]"; break;
        case MathOp::Neg: expr = "-x[i]"; break;
        case MathOp::Exp: expr = "mlk_exp(x[i])"; break;
        case MathOp::Log: expr = "mlk_log(x[i])"; break;
        case MathOp::Sin: expr = "mlk_sin(x[i])"; break;
        case MathOp::Cos: expr = "mlk_cos(x[i])"; break;
        case MathOp::Tan: expr = "mlk_tan(x[i])"; break;
        case MathOp::Tanh: expr = "mlk_tanh(x[i])"; break;
        case MathOp::Sqrt: expr = "mlk_sqrt(x[i])"; break;
        case MathOp::Rsqrt: expr = "1.0 / mlk_sqrt(x[i])"; break;
        case MathOp::Erf: expr = "mlk_erf(x[i])"; break;
        case MathOp::Gelu:
            expr = "0.5 * x[i] * (1.0 + mlk_tanh(0.7978845608028654 * (x[i] "
                   "+ 0.044715 * x[i] * x[i] * x[i])))";
            break;
        default: expr = "x[i]"; break;
    }
    (void)symbols;
    out += "        out[i] = ";
    out += expr;
    out += ";\n";
}
}  // namespace

Result<std::string> emitCppSource(const KernelModule& kernel,
                                  SymbolTable& symbols) {
    if (kernel.nodes.empty()) {
        return err(ErrorCode::InvalidGraph, "cannot emit empty kernel module");
    }
    std::string out;
    out += "// Generated by MLK+ (mlk_backend_cpu::emitCppSource).\n";
    out += "// Kernel: " + symbols.text(kernel.name) + "  hash: " +
           std::to_string(kernel.hash()) + "\n";
    out += "// Target feature gates are recorded per realization (Rule 148).\n";
    out += "#include <cmath>\n#include <cstdint>\n\n";
    out += "static inline double mlk_sin(double x){return ::sin(x);}\n";
    out += "static inline double mlk_cos(double x){return ::cos(x);}\n";
    out += "static inline double mlk_tan(double x){return ::tan(x);}\n";
    out += "static inline double mlk_tanh(double x){return ::tanh(x);}\n";
    out += "static inline double mlk_exp(double x){return ::exp(x);}\n";
    out += "static inline double mlk_log(double x){return ::log(x);}\n";
    out += "static inline double mlk_sqrt(double x){return ::sqrt(x);}\n";
    out += "static inline double mlk_erf(double x){return ::erf(x);}\n\n";
    out += "extern \"C\" void mlk_kernel(const double* x, const double* y, "
           "double* out, int64_t n) {\n";
    out += "    for (int64_t i = 0; i < n; ++i) {\n";
    for (const auto& n : kernel.nodes) {
        if (n.op == KernelOp::Compute) emitCompute(out, n.math, symbols);
    }
    out += "    }\n}\n";
    return out;
}

}  // namespace mlk
