// MLK+ pass contract + registry (spec §6/§7; Rules 142, 150).
//
// Every pass declares a contract: required/produced analyses, invalidated
// analyses, supported tiers, determinism, default budget, and a kill switch.
// The registry is the generated source of truth (pass_registry.inc is
// regenerated by scripts/gen_pass_registry.py from MLK_REGISTER_PASS uses).
#pragma once

#include <vector>

#include "mlk/core/small_vector.h"
#include "mlk/core/symbol_table.h"
#include "mlk/pass/pass.h"

namespace mlk {

struct PassContract {
    SymbolId name{kInvalidSymbolId};
    PassKind kind{PassKind::Transform};
    SmallVector<SymbolId, 4> requiredProperties{};   // e.g. "ir.verified"
    SmallVector<SymbolId, 4> producedProperties{};
    SmallVector<SymbolId, 4> invalidatedAnalyses{};
    SmallVector<Tier, 4> supportedTiers{};
    bool deterministic{true};
    PassBudget defaultBudget{};
    bool killSwitchable{true};
};

/// Static pass registry. Registration happens via PassRegistrar at static
/// init (deterministic order by name; Rule 143).
///
/// Resolution is BY TEXT (Rule 16: "ids are table-scoped, so passes carry
/// text, not ids"). The registry is a process-wide singleton while every
/// embedding (test, CLI, pipeline) interns names into its OWN SymbolTable;
/// raw SymbolId values are meaningless across tables — an id that means
/// "poly.synth" in one table can be "memory.place" in another. Matching
/// raw ids therefore returned WRONG PASSES whenever a caller's table
/// numbered names differently from the first-registered table (observed
/// live: byName("poly.synth") dispatched memory.place). Callers pass the
/// table they interned with; the registry compares name TEXT.
class PassRegistry {
public:
    [[nodiscard]] static PassRegistry& instance();

    void add(PassContract contract, Pass* pass);

    /// Resolves `name` (interned in `symbols`) by TEXT. The pass registry
    /// outlives any single SymbolTable; text is the only stable identity.
    [[nodiscard]] Pass* byName(const SymbolTable& symbols, SymbolId name);
    [[nodiscard]] const PassContract* contractByName(
        const SymbolTable& symbols, SymbolId name) const;

    [[nodiscard]] std::size_t size() const { return entries_.size(); }

    struct Entry {
        PassContract contract;
        Pass* pass{nullptr};
        /// Stable textual identity (Rule 16) — captured from
        /// pass->nameText() at registration; never null for real passes.
        const char* nameText{nullptr};
    };

    [[nodiscard]] const std::vector<Entry>& entries() const {
        return entries_;
    }

private:
    std::vector<Entry> entries_;
};

/// Registration helper (translation-unit-local statics; deterministic).
struct PassRegistrar {
    PassRegistrar(SymbolTable& symbols, const char* passName, PassKind kind,
                  std::initializer_list<const char*> required,
                  std::initializer_list<const char*> produced,
                  std::initializer_list<const char*> invalidated,
                  std::initializer_list<Tier> tiers, Pass* pass) {
        PassContract c;
        c.name = symbols.intern(passName);
        c.kind = kind;
        for (const char* r : required) {
            c.requiredProperties.push_back(symbols.intern(r));
        }
        for (const char* p : produced) {
            c.producedProperties.push_back(symbols.intern(p));
        }
        for (const char* i : invalidated) {
            c.invalidatedAnalyses.push_back(symbols.intern(i));
        }
        for (const Tier t : tiers) c.supportedTiers.push_back(t);
        PassRegistry::instance().add(std::move(c), pass);
    }
};

}  // namespace mlk
