// MLK+ superoptimizer plugin interface + candidates + proofs (spec §6/§13;
// Rules 50-53, 60: verified certificates, modular, domain-gated, killable).
#pragma once

#include "mlk/core/result.h"
#include "mlk/core/symbol_table.h"
#include "mlk/ir/math_graph.h"
#include "mlk/proof/accuracy_contract.h"
#include "mlk/type/domain_profile.h"

namespace mlk {

/// Proof/certificate attached to every candidate (Rule 52: no opaque
/// candidates; Rule 150: machine-checkable).
struct SuperoptProof {
    enum class Kind : uint8_t {
        AlgebraicIdentity,
        DomainConstrained,
        ErrorBound,
        TestEvidence,
    };
    Kind kind{Kind::TestEvidence};
    SmallVector<SymbolId, 4> appliedRules{};
    std::optional<double> errorBoundUlps{};
    std::optional<double> maxAbsError{};
    /// Machine-checkable predicate list (verifier re-runs these).
    SmallVector<SymbolId, 4> predicates{};

    [[nodiscard]] HashValue hash() const noexcept {
        HashValue h = hashU64(static_cast<uint64_t>(kind));
        for (std::size_t i = 0; i < appliedRules.size(); ++i) {
            h = hashCombine(h, hashU64(appliedRules[i]));
        }
        if (errorBoundUlps) h = hashCombine(h, hashF64(*errorBoundUlps));
        return h;
    }
};

/// A candidate realization generated by a superoptimizer (Rule 52 fields).
struct RealizationCandidate {
    MathGraph transformed{};
    SuperoptProof proof{};
    double estimatedSpeedup{1.0};
    SymbolId origin{constants::kInvalidId};
    SymbolId fallbackPlan{constants::kInvalidId};
};

/// Superoptimizer plugin (spec §13): modular, domain-gated, independently
/// killable (Rule 60).
class Superoptimizer {
public:
    virtual ~Superoptimizer() = default;

    [[nodiscard]] virtual SymbolId name() const = 0;
    [[nodiscard]] virtual bool canApply(const MathGraph& graph,
                                        const MathDomainProfile& profile) = 0;
    [[nodiscard]] virtual Result<SmallVector<RealizationCandidate, 8>>
    generate(const MathGraph& graph, const AccuracyContract& contract,
             const MathDomainProfile& profile) = 0;
};

}  // namespace mlk
