#!/usr/bin/env python3
"""Regenerates docs/pass_registry.md from the registered pass catalog
(layout spec §7; Rule 142: every pass declares a contract). The registry
source of truth is compiler/src/passes/*/; run after adding a pass."""
import os, re, sys

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
PASSES_DIR = os.path.join(ROOT, "compiler", "src", "passes")

def find_registrations():
    """Finds registerPass(...) calls: name comes from the PassBase ctor."""
    entries = []
    pat = re.compile(r'\w+\(\s*symbols,\s*"([a-z_.0-9]+)"\s*,\s*PassKind::(\w+)')
    for dirpath, _, files in os.walk(PASSES_DIR):
        for f in files:
            if not f.endswith(".cpp"):
                continue
            path = os.path.join(dirpath, f)
            with open(path) as fh:
                text = fh.read()
            for m in pat.finditer(text):
                entries.append((m.group(1), m.group(2), os.path.relpath(path, ROOT)))
    return sorted(set(entries))

def main():
    entries = find_registrations()
    lines = ["# MLK+ Pass Registry", "",
             "Auto-generated by scripts/gen_pass_registry.py. Do not edit.",
             "", "| Pass | Kind | Source |", "|---|---|---|"]
    for name, kind, src in entries:
        lines.append(f"| `{name}` | {kind.lower()} | `{src}` |")
    lines.append("")
    lines.append(f"Total: {len(entries)} registered passes.")
    out = os.path.join(ROOT, "docs", "pass_registry.md")
    os.makedirs(os.path.dirname(out), exist_ok=True)
    with open(out, "w") as f:
        f.write("\n".join(lines) + "\n")
    print(f"wrote {out} ({len(entries)} passes)")

if __name__ == "__main__":
    sys.exit(main())
