# Helper: define an MLK+ static library with standard flags/sanitizers.
# Usage: mlk_add_library(<name> INCLUDE_DIR <dir> SOURCES <src...>
#                        [DEPS <targets...>] [PUBLIC_DEPS <targets...>])
function(mlk_add_library name)
    cmake_parse_arguments(ARG "" "INCLUDE_DIR" "SOURCES;DEPS;PUBLIC_DEPS" ${ARGN})
    add_library(${name} STATIC)
    target_sources(${name} PRIVATE ${ARG_SOURCES})
    if(ARG_INCLUDE_DIR)
        target_include_directories(${name}
            PUBLIC $<BUILD_INTERFACE:${CMAKE_CURRENT_SOURCE_DIR}/${ARG_INCLUDE_DIR}>)
    endif()
    if(ARG_PUBLIC_DEPS)
        target_link_libraries(${name} PUBLIC ${ARG_PUBLIC_DEPS})
    endif()
    if(ARG_DEPS)
        target_link_libraries(${name} PRIVATE ${ARG_DEPS})
    endif()
    mlk_apply_flags(${name})
    mlk_apply_sanitizers(${name})
    set(MLK_ALL_SOURCES ${MLK_ALL_SOURCES} ${ARG_SOURCES} PARENT_SCOPE)
endfunction()

function(mlk_add_executable name)
    cmake_parse_arguments(ARG "" "" "SOURCES;DEPS" ${ARGN})
    add_executable(${name} ${ARG_SOURCES})
    target_link_libraries(${name} PRIVATE ${ARG_DEPS})
    mlk_apply_flags(${name})
    mlk_apply_sanitizers(${name})
    set(MLK_ALL_SOURCES ${MLK_ALL_SOURCES} ${ARG_SOURCES} PARENT_SCOPE)
endfunction()
